title: Highlights âœï¸ğŸ“š
description: A minisite for book and article highlights.
url: https://matteotagliatti.github.io
baseurl: /highlights

github: https://github.com/matteotagliatti/highlights
website: https://matteotagliatti.it

collections:
  highlights:
    output: true
    permalink: :name
    sort_by: year

defaults:
  - scope:
      path: ""
      type: "highlights"
    values:
      layout: "highlight"

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md